version: 2
updates:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    # default is / which breaks drone
    pull-request-branch-name:
      separator: "-"
    # not created automatically for version updates so only security ones are created
    # https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
    open-pull-requests-limit: 0 
    